name: Build and Test (branches)
on:
  push:
    branches:    
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Lint code
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
        mypy semversioner tests
    - name: Build and test
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine flake8
        pip install -r requirements.txt
        pytest --junitxml="test-reports/test-report.xml"
